# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 自动签到

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check in
      id: checkin
      run: |
        python main.py
      env:
        # MIHOYOBBS_LOGIN_TICKET: ${{secrets.MIHOYOBBS_LOGIN_TICKET}}
        # MIHOYOBBS_STUID: ${{secrets.MIHOYOBBS_STUID}}
        # MIHOYOBBS_STOKEN: ${{secrets.MIHOYOBBS_STOKEN}}
        MIHOYOBBS_CREDIT: ${{secrets.MIHOYOBBS_CREDIT}}
        MIHOYOBBS_COOKIES: ${{secrets.MIHOYOBBS_COOKIES}}
    - name: Save credit
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MIHOYOBBS_CREDIT'
        # value: '${{ job.status == "success" && steps.checkin.outputs.MIHOYOBBS_CREDIT || "" }}'
        value: ${{ steps.checkin.outputs.MIHOYOBBS_CREDIT }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - name: Clear credit
      if: ${{ failure() }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MIHOYOBBS_CREDIT'
        value: ''
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    
      
